"""Add year column to earthquakes

Revision ID: 50b5778d866d
Revises: 68627545718c
Create Date: 2025-06-08 19:20:08.966619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50b5778d866d'
down_revision = '68627545718c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('earthquakes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('earthquakes', schema=None) as batch_op:
        batch_op.drop_column('year')

    # ### end Alembic commands ###
