"""Create earthquakes table

Revision ID: 68627545718c
Revises: 
Create Date: 2025-06-08 19:18:33.420046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68627545718c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('earthquakes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('magnitude', sa.Float(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('earthquakes')
    # ### end Alembic commands ###
